import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.goto('http://127.0.0.1:43123/', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /Team thumbnail/i }).click();
await page.waitForSelector('text=Create a Love\'s Team thumbnail', { timeout: 10000 });
await page.getByRole('button', { name: /Load practice team/i }).click();
await page.waitForSelector('text=Jared Thueson', { timeout: 15000 });
await page.waitForSelector('img[alt="Love\'s Team thumbnail preview"]', { timeout: 15000 });
const downloadBtn = page.getByRole('button', { name: /Download thumbnail PNG/i });
await downloadBtn.waitFor({ state: 'visible' });
console.log(JSON.stringify({ ok: true }));
await browser.close();
